package com.fb;
// Generated 8 Jan, 2018 11:44:41 PM by Hibernate Tools 4.3.1



/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private String email;
     private String name;
     private String password;
     private Task task;

    public Student() {
    }

	
    public Student(String email, String name, String password) {
        this.email = email;
        this.name = name;
        this.password = password;
    }
    public Student(String email, String name, String password, Task task) {
       this.email = email;
       this.name = name;
       this.password = password;
       this.task = task;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Task getTask() {
        return this.task;
    }
    
    public void setTask(Task task) {
        this.task = task;
    }




}


