package com.fb;
// Generated 8 Jan, 2018 11:44:41 PM by Hibernate Tools 4.3.1



/**
 * Task generated by hbm2java
 */
public class Task  implements java.io.Serializable {


     private String email;
     private Student student;
     private String todo;
     private String doing;
     private String done;

    public Task() {
    }

	
    public Task(Student student) {
        this.student = student;
    }
    public Task(Student student, String todo, String doing, String done) {
       this.student = student;
       this.todo = todo;
       this.doing = doing;
       this.done = done;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public String getTodo() {
        return this.todo;
    }
    
    public void setTodo(String todo) {
        this.todo = todo;
    }
    public String getDoing() {
        return this.doing;
    }
    
    public void setDoing(String doing) {
        this.doing = doing;
    }
    public String getDone() {
        return this.done;
    }
    
    public void setDone(String done) {
        this.done = done;
    }




}


